"""empty message

Revision ID: 1e4bbc0669c8
Revises: 1564fcd98c34
Create Date: 2024-12-24 20:21:24.423236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4bbc0669c8'
down_revision: Union[str, None] = '1564fcd98c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_size_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_items', 'item_sizes', ['item_size_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'item_size_id')
    # ### end Alembic commands ###
