"""delivery method

Revision ID: 44d1a0861340
Revises: 574eef5bcc04
Create Date: 2025-02-06 19:48:54.091869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d1a0861340'
down_revision: Union[str, None] = '574eef5bcc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    delivery_methods = sa.Enum('CDEK', 'DELOVIE_LINII', name='deliverymethod')
    delivery_methods.create(op.get_bind(), checkfirst=True)
    
    op.add_column('orders', sa.Column('other_delivery_method', delivery_methods, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'other_delivery_method')
    # ### end Alembic commands ###
