"""qwer

Revision ID: 5003652f7e1d
Revises: 44d1a0861340
Create Date: 2025-02-06 22:36:59.729084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5003652f7e1d'
down_revision: Union[str, None] = '44d1a0861340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
