"""address details

Revision ID: 574eef5bcc04
Revises: 62f1a779890a
Create Date: 2025-02-04 00:55:34.189934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574eef5bcc04'
down_revision: Union[str, None] = '62f1a779890a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column('orders', sa.Column('address_details', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_price', sa.Integer(), nullable=True))

    op.execute("UPDATE orders SET address_details = 'default_address' WHERE address_details IS NULL")
    op.execute("UPDATE orders SET delivery_price = 0 WHERE delivery_price IS NULL")

    op.alter_column('orders', 'address_details', nullable=False)
    op.alter_column('orders', 'delivery_price', nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_price')
    op.drop_column('orders', 'address_details')
    # ### end Alembic commands ###
