"""order details

Revision ID: 62f1a779890a
Revises: c511743cb5ca
Create Date: 2024-12-27 21:49:28.129143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f1a779890a'
down_revision: Union[str, None] = 'c511743cb5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('fio', sa.String(), nullable=False, server_default=''))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=False, server_default=''))
    op.add_column('orders', sa.Column('address', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'fio')
    # ### end Alembic commands ###
