"""add ative field on items

Revision ID: 8081a91cd986
Revises: 8a57f66f9561
Create Date: 2024-12-13 14:01:07.445918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8081a91cd986'
down_revision: Union[str, None] = '8a57f66f9561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'active')
    # ### end Alembic commands ###
