"""payment for orders

Revision ID: 8a57f66f9561
Revises: b7258b572408
Create Date: 2024-11-25 22:55:45.148311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a57f66f9561'
down_revision: Union[str, None] = 'b7258b572408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = sa.Enum('PENDING', 'WAITING_FOR_CAPTURE', 'SUCCEEDED', 'CANCELED', name='paymentstatus')
    payment_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('orders', sa.Column('payment_id', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('payment_status', sa.Enum('PENDING', 'WAITING_FOR_CAPTURE', 'SUCCEEDED', 'CANCELED', name='paymentstatus'), nullable=False))
    op.add_column('orders', sa.Column('receipt_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receipt_email')
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'payment_id')
    
    # Drop the enum type
    op.execute('DROP TYPE IF EXISTS paymentstatus')
    # ### end Alembic commands ###
