"""add product categories

Revision ID: 982d10ada902
Revises: d1da4316a51c
Create Date: 2024-12-25 22:16:32.278727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982d10ada902'
down_revision: Union[str, None] = 'd1da4316a51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    flavour_enum = sa.Enum('BARANINA', 'INDEYKA', 'OLENINA', 'YTKA', name='productflavour')
    flavour_enum.create(op.get_bind(), checkfirst=True)
    
    category_enum = sa.Enum('PUPPIES', 'CATS_1', 'DOGS_1_6', 'DOGS_7', 'ZAPECHENIY', name='productcategory')
    category_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('items', sa.Column('favour', sa.Enum('BARANINA', 'INDEYKA', 'OLENINA', 'YTKA', name='productflavour'), nullable=True))
    op.add_column('items', sa.Column('category', sa.Enum('PUPPIES', 'CATS_1', 'DOGS_1_6', 'DOGS_7', 'ZAPECHENIY', name='productcategory'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    op.drop_column('items', 'favour')
    # ### end Alembic commands ###
