"""fix type in flavour

Revision ID: c511743cb5ca
Revises: 982d10ada902
Create Date: 2024-12-25 22:46:48.569754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c511743cb5ca'
down_revision: Union[str, None] = '982d10ada902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('flavour', sa.Enum('BARANINA', 'INDEYKA', 'OLENINA', 'YTKA', name='productflavour'), nullable=True))
    op.drop_column('items', 'favour')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('favour', postgresql.ENUM('BARANINA', 'INDEYKA', 'OLENINA', 'YTKA', name='productflavour'), autoincrement=False, nullable=True))
    op.drop_column('items', 'flavour')
    # ### end Alembic commands ###
