"""empty message

Revision ID: d1da4316a51c
Revises: 1e4bbc0669c8
Create Date: 2024-12-25 13:00:21.550847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1da4316a51c'
down_revision: Union[str, None] = '1e4bbc0669c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_size', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('item_price', sa.Integer(), nullable=False))
    op.drop_constraint('order_items_item_size_id_fkey', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'item_size_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_size_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_items_item_size_id_fkey', 'order_items', 'item_sizes', ['item_size_id'], ['id'])
    op.drop_column('order_items', 'item_price')
    op.drop_column('order_items', 'item_size')
    # ### end Alembic commands ###
